### ISSUE TITLE
Refactor authentication to use JWT verification

### ISSUE THREAD

**Issue by evansiroky** [catalogueglobal/datatools-server#105]
It appears that the current authentication system merely verifies a token is valid and does not check that it was signed in the way we expect it to be signed.  We should be verifying that the JWT signature is expected by verifying it against our own secret.  See [example in analysis-backend](https://github.com/conveyal/analysis-backend/blob/dev/src/main/java/com/conveyal/taui/AnalysisServer.java#L184-L191).

**Comment by landonreed** [comment]
I tried pasting the example code block into the `Auth0Connection#checkUser` method, but I'm running into a `java.security.SignatureException: signature verification failed` exception.  However, it does seem to work with the suggestion [here](https://github.com/auth0/java-jwt/issues/61#issuecomment-239213881): `JWTVerifier verifier = new JWTVerifier(new Base64().decode(secret));`

Thoughts?

**Comment by evansiroky** [comment]
Yeah, the code in analysis assumes the use a base64 encoded key.
