### ISSUE TITLE
Pom blurb is filtering out logback.xml

### ISSUE THREAD

**Issue by landonreed** [catalogueglobal/datatools-server#123]
@evansiroky, I think some changes made to display the server's commit/version are causing the logback.xml file (in `src/main/resources`) to be ignored. 

https://github.com/catalogueglobal/datatools-server/blob/d954623333d2ae9e2cc842a3504fe2724502dbe3/pom.xml#L57-L67

**Comment by evansiroky** [comment]
Yeah, I've noticed that and have added it back here: https://github.com/catalogueglobal/datatools-server/pull/118/files#diff-600376dffeb79835ede4a0b285078036R27 and here: https://github.com/catalogueglobal/datatools-server/pull/108/files#diff-600376dffeb79835ede4a0b285078036R27
