### ISSUE TITLE
Update VEX URL

### ISSUE THREAD

**Issue by abyrd** [catalogueglobal/datatools-server#20]
Data tools is the only Conveyal product still using the old C VEX URL pattern. We should update it so our VEX nginx proxy doesn't need to contain URL rewrite rules. Alternatively update everything to use the old VEX URL pattern which @mattwigway pointed out is probably better since it uses named URL parameters.

**Comment by landonreed** [comment]
What is the new pattern it should follow @abyrd ?

**Comment by aguiraf** [comment]
It should be:  <server:port>/min_lat,min_lon,max_lat,max_lon[.pbf|.vex] 
just pushed a PR

**Comment by abyrd** [comment]
Thanks @aguiraf
