### ISSUE TITLE
gtfs read issues

### ISSUE THREAD

**Issue by evansiroky** [catalogueglobal/datatools-server#55]
* does not read in calendar_dates
* does not read stop's zone id

**Comment by landonreed** [comment]
@evansiroky, I can you close this if you agree it's no longer an issue (thanks to your work in conveyal/gtfs-lib#141)? I believe zone_id support was added some time ago, too.

**Comment by landonreed** [comment]
Actually, this is more or less a dupicate of #80, so I'm going to close.
