### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by a1ex4nd3r** [catalogueglobal/datatools-server#61]
Hi,

When I try to build the project I am getting this error when the tests start: [http://prntscr.com/hj0j3v](http://prntscr.com/hj0j3v)
I do not see any info about a mongodb setup in the docs. I've started up mongodb locally but nothing changed. Any suggestions?

**Comment by landonreed** [comment]
The docs update had not been triggered properly.  Mongo (and Postgres) setup information can be found here now: http://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment/#database-setup
