### ISSUE TITLE
Cannot add an Agency - /api/editor/secure/agency has not been mapped in Spark

### ISSUE THREAD

**Issue by heshamghandour** [catalogueglobal/datatools-server#63]
Hi!

Just set up the service but when trying to add an agency, it stops working, and this message appears on the server console:

`Dec 14 19:40:19.190 [qtp2073480674-39] INFO  spark.http.matching.MatcherFilter - The requested route [/api/editor/secure/agency] has not been mapped in Spark`

Same happens with other functions like:

`Dec 14 19:39:55.922 [qtp2073480674-16] INFO  spark.http.matching.MatcherFilter - The requested route [/api/editor/secure/agency/new/uploadbranding] has not been mapped in Spark`

Any known issues there?
Thanks!

**Comment by landonreed** [comment]
It's likely that your `server.yml` config does not have the editor module enabled.  However, `v3.0.0` does not have full support for the editor at the moment, so I would recommend using 2.x if you're looking to use the GTFS editor.

**Comment by heshamghandour** [comment]
True! Using v2.0.0 fixed the issue thanks.
