### ISSUE TITLE
Auth0-Endpoint deprecations: https://client.auth0.com/user/ssodata returns 404

### ISSUE THREAD

**Issue by Rillke** [catalogueglobal/datatools-server#87]
In the network monitor tab of my browser, I see a 404 recorded to the ssodata-endpoint of Auth0. This may caused by the [ssodata endpoint deprecation](https://auth0.com/docs/migrations#introducing-lock-v11-and-auth0-js-v9). According to [a discussion](https://community.auth0.com/t/cors-error-despite-correct-settings-in-newly-created-tenant/9151/20), new tenants don’t have the ability to use older versions of Lock in embedded form and they also don’t have access to old legacy grant flows.

Does this mean, there is currently no means to successfully install and use catalogueglobal/datatools-server if you do not have an old Auth0 tenant?

![firefox web console](https://user-images.githubusercontent.com/2311611/39968619-638d833e-56d0-11e8-8ee7-4b7e20e09c79.png)
![firefox network console](https://user-images.githubusercontent.com/2311611/39968640-ade3bf8e-56d0-11e8-859b-7d59bdc4cfd0.png)

**Comment by Rillke** [comment]
Is there any Auth0-compatible replacement for the meantime?

**Comment by Rillke** [comment]
Closing in favour of catalogueglobal/datatools-ui/issues/158

**Comment by rbawaskar** [comment]
The datatools-server is using deprecated Auth0 API  "/tokeninfo". 
The issue affects both datatools-server and datatools-ui.
